### ISSUE TITLE
mobile responsivity: container fails to expand vertically

### ISSUE THREAD

**Issue by Felicious** [Felicious/felicious.github.io#3]
![image](https://user-images.githubusercontent.com/23611711/147724672-e25b62ba-7bdd-4301-878d-1b0c0a54a105.png)

Expected Behavior: when viewing on mobile, there are no horizontal gaps and the image takes up as much vertical space as allowed. When viewing on desktop, the image grows to a max height of 70% and the sides are filled in by horizontal gaps.
```css
@media (min-width: 401px) {
  .container > * {
    height: 70%;
    width: 35%;
  }
}
```

However, it currently seems like the container does not grow to the vertical length of the screen. Why?
